#!/usr/bin/env bash

# Mostly taken from this excellent blogpost by Penz:
# http://www.lpenz.org/articles/nixchannel/index.html

set -euo pipefail

OUTPUT=$1/bio-channel

mkdir -p "$OUTPUT"/cache

pushd pkgs || exit 1

tar -cJf "$OUTPUT"/nixexprs.tar.xz ./*.nix ./**/* \
    --transform "s,^,${PWD##*/}/," \
    --owner=0 --group=0 --mtime="1970-01-01 00:00:00 UTC"

touch "$OUTPUT"/index.html

printf 'pc5/cache' > "$OUTPUT"/pc5

nix-build

sudo nix sign-paths -k "$NIX_SECRET_KEY_FILE"
nix copy --to "file:///$OUTPUT/cache"

# not working for some reason
# nix path-info --store "file:///$OUTPUT/cache" --json | json_pp

popd || exit 1

tar czvf ./cache.tar.gz "$OUTPUT"

